import { contextBridge, ipcRenderer } from 'electron';

contextBridge.exposeInMainWorld('api', {
  getProductByBarcode: (barcode: string, storeId: string) => ipcRenderer.invoke('get-product-by-barcode', barcode, storeId),
  getAllProducts: (includeArchived?: boolean) => ipcRenderer.invoke('get-all-products', includeArchived),
  saveManualProduct: (product: any) => ipcRenderer.invoke('save-manual-product', product),
  saveSale: (sale: any) => ipcRenderer.invoke('save-sale', sale),
  importXmlProducts: (xmlData: string, storeId: string) => ipcRenderer.invoke('import-xml-products', xmlData, storeId),
  getSyncStatus: () => ipcRenderer.invoke('get-sync-status'),
  getRepairs: () => ipcRenderer.invoke('get-repairs'),
  getRepairHistory: (repairId: string) => ipcRenderer.invoke('get-repair-history', repairId),
  verifyUserPassword: (data: any) => ipcRenderer.invoke('verify-user-password', data),
  addRepairLog: (data: any) => ipcRenderer.invoke('add-repair-log', data),
  saveRepair: (repair: any) => ipcRenderer.invoke('save-repair', repair),
  updateRepairStatus: (data: any) => ipcRenderer.invoke('update-repair-status', data),
  updateRepairNotes: (data: any) => ipcRenderer.invoke('update-repair-notes', data),
  updateRepairPayment: (data: any) => ipcRenderer.invoke('update-repair-payment', data),
  uploadRepairImage: (data: any) => ipcRenderer.invoke('upload-repair-image', data),
  downloadProtocolTemplate: () => ipcRenderer.invoke('download-protocol-template'),
  getStores: (includeArchived?: boolean) => ipcRenderer.invoke('get-stores', includeArchived),
  saveStore: (store: {id?: string, name: string}) => ipcRenderer.invoke('save-store', store),
  archiveStore: (data: {id: string, archived: boolean}) => ipcRenderer.invoke('archive-store', data),
  getUsers: () => ipcRenderer.invoke('get-users'),
  saveUser: (user: any) => ipcRenderer.invoke('save-user', user),
  login: (credentials: any) => ipcRenderer.invoke('login', credentials),
  getCustomers: () => ipcRenderer.invoke('get-customers'),
  getSalesByCustomer: (customerId: string) => ipcRenderer.invoke('get-sales-by-customer', customerId),
  getRepairsByCustomer: (customerId: string) => ipcRenderer.invoke('get-repairs-by-customer', customerId),
  saveCustomer: (customer: any) => ipcRenderer.invoke('save-customer', customer),
  getTasks: () => ipcRenderer.invoke('get-tasks'),
  saveTask: (task: any) => ipcRenderer.invoke('save-task', task),
  deleteTask: (id: string) => ipcRenderer.invoke('delete-task', id),
  toggleTask: (id: string, status: string) => ipcRenderer.invoke('toggle-task', { id, status }),
  completeTask: (id: string, photo?: string, justification?: string) => ipcRenderer.invoke('complete-task', { id, photo, justification }),
  getCommissions: () => ipcRenderer.invoke('get-commissions'),
  getExpenses: () => ipcRenderer.invoke('get-expenses'),
  saveExpense: (expense: any) => ipcRenderer.invoke('save-expense', expense),
  deleteExpense: (id: string) => ipcRenderer.invoke('delete-expense', id),
  getExpenseCategories: () => ipcRenderer.invoke('get-expense-categories'),
  saveExpenseCategory: (category: any) => ipcRenderer.invoke('save-expense-category', category),
  getBudgets: () => ipcRenderer.invoke('get-budgets'),
  saveBudget: (budget: any) => ipcRenderer.invoke('save-budget', budget),
  getFinancialSummary: () => ipcRenderer.invoke('get-financial-summary'),
  getDetailedReports: (filters: any) => ipcRenderer.invoke('get-detailed-reports', filters),
  getDashboardStats: () => ipcRenderer.invoke('get-dashboard-stats'),
  getLowStockItems: () => ipcRenderer.invoke('get-low-stock-items'),
  getStaleStockItems: () => ipcRenderer.invoke('get-stale-stock-items'),
  getSettings: () => ipcRenderer.invoke('get-settings'),
  saveSettings: (settings: {key: string, value: string}[]) => ipcRenderer.invoke('save-settings', settings),
  archiveProduct: (data: {id: string, archived: boolean}) => ipcRenderer.invoke('archive-product', data),
  updateInventoryQuantity: (data: {productId: string, storeId: string, quantity: number, minStock?: number, saleToleranceDays?: number}) => ipcRenderer.invoke('update-inventory-quantity', data),
  printReceipt: (data: {sale: any, storeName: string, logo?: string, deviceName?: string}) => ipcRenderer.invoke('print-receipt', data),
  printRepairReceipt: (data: {repair: any, storeName: string, logo?: string, deviceName?: string}) => ipcRenderer.invoke('print-repair-receipt', data),
  getPrinters: () => ipcRenderer.invoke('get-printers'),
  getCurrentRegister: (data: { storeId: string }) => ipcRenderer.invoke('get-current-register', data),
  openRegister: (data: { storeId: string, userName: string, openingBalance: number }) => ipcRenderer.invoke('open-register', data),
  getRegisterData: (data: { storeId: string, openedAt: string }) => ipcRenderer.invoke('get-register-data', data),
  closeRegister: (data: { id: string, closingBalance: number, reportedBalance: number, totals: any, notes: string }) => ipcRenderer.invoke('close-register', data),
  getRegisterHistory: () => ipcRenderer.invoke('get-register-history'),
  testPrinter: (data: {deviceName: string}) => ipcRenderer.invoke('test-printer', data),
  printUSB: (vid: number, pid: number, data: any) => ipcRenderer.invoke('print-usb', { vid, pid, data }),
  printRaw: (data: any, interfaceName?: string) => ipcRenderer.invoke('print-raw', { data, interfaceName }),
  printSilent: (html: string, deviceName?: string) => ipcRenderer.invoke('print-silent', { html, deviceName }),
  exportReportToPDF: (data: any) => ipcRenderer.invoke('export-report-pdf', data),
  exportReportToExcel: (data: any) => ipcRenderer.invoke('export-report-excel', data),
  uploadProductImage: (data: {barcode: string, base64Data: string}) => ipcRenderer.invoke('upload-product-image', data),
  getLibraryItems: () => ipcRenderer.invoke('get-library-items'),
  saveLibraryItem: (item: any) => ipcRenderer.invoke('save-library-item', item),
  uploadLibraryImage: (data: {name: string, base64Data: string}) => ipcRenderer.invoke('upload-library-image', data),
  uploadUserPhoto: (data: {userId: string, base64Data: string}) => ipcRenderer.invoke('upload-user-photo', data),
  isCloudConfigured: () => ipcRenderer.invoke('is-cloud-configured'),
  getAppTitle: () => ipcRenderer.invoke('get-app-title'),
  usbDirectPrint: (data: { buffer: Uint8Array }) => ipcRenderer.invoke('usb-direct-print', data),
  listUsbDevices: () => ipcRenderer.invoke('list-usb-devices'),
  runPrinterSetup: () => ipcRenderer.invoke('run-printer-setup'),
  minimizeWindow: () => ipcRenderer.send('window-minimize'),
  maximizeWindow: () => ipcRenderer.send('window-maximize'),
  closeWindow: () => ipcRenderer.send('window-close'),
  setZoom: (factor: number) => ipcRenderer.send('window-set-zoom', factor),
  checkForUpdates: () => ipcRenderer.invoke('check-for-updates'),
  onUpdateAvailable: (callback: (info: any) => void) => {
    const subscription = (_event: any, info: any) => callback(info);
    ipcRenderer.on('update-available', subscription);
    return () => ipcRenderer.removeListener('update-available', subscription);
  },
  onUpdateProgress: (callback: (progress: any) => void) => {
    const subscription = (_event: any, progress: any) => callback(progress);
    ipcRenderer.on('update-progress', subscription);
    return () => ipcRenderer.removeListener('update-progress', subscription);
  },
  onUpdateDownloaded: (callback: (info: any) => void) => {
    const subscription = (_event: any, info: any) => callback(info);
    ipcRenderer.on('update-downloaded', subscription);
    return () => ipcRenderer.removeListener('update-downloaded', subscription);
  },
});
